// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MCMC_loop
List MCMC_loop(List state, Nullable<NumericVector> D, double mu_a, double tau_a, double mu_b, double tau_b, double mu_u, double tau_u, double gamma, double delta, double tau, int K, List W_list, SEXP W_miss, Nullable<IntegerVector> idx1, Nullable<IntegerVector> idx0, int n_iter, int n_burnin, int n_thin, double tol_shift, unsigned int max_iter_shift);
RcppExport SEXP _bayesodt_MCMC_loop(SEXP stateSEXP, SEXP DSEXP, SEXP mu_aSEXP, SEXP tau_aSEXP, SEXP mu_bSEXP, SEXP tau_bSEXP, SEXP mu_uSEXP, SEXP tau_uSEXP, SEXP gammaSEXP, SEXP deltaSEXP, SEXP tauSEXP, SEXP KSEXP, SEXP W_listSEXP, SEXP W_missSEXP, SEXP idx1SEXP, SEXP idx0SEXP, SEXP n_iterSEXP, SEXP n_burninSEXP, SEXP n_thinSEXP, SEXP tol_shiftSEXP, SEXP max_iter_shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type mu_a(mu_aSEXP);
    Rcpp::traits::input_parameter< double >::type tau_a(tau_aSEXP);
    Rcpp::traits::input_parameter< double >::type mu_b(mu_bSEXP);
    Rcpp::traits::input_parameter< double >::type tau_b(tau_bSEXP);
    Rcpp::traits::input_parameter< double >::type mu_u(mu_uSEXP);
    Rcpp::traits::input_parameter< double >::type tau_u(tau_uSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< List >::type W_list(W_listSEXP);
    Rcpp::traits::input_parameter< SEXP >::type W_miss(W_missSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type idx1(idx1SEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type idx0(idx0SEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type n_burnin(n_burninSEXP);
    Rcpp::traits::input_parameter< int >::type n_thin(n_thinSEXP);
    Rcpp::traits::input_parameter< double >::type tol_shift(tol_shiftSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type max_iter_shift(max_iter_shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(MCMC_loop(state, D, mu_a, tau_a, mu_b, tau_b, mu_u, tau_u, gamma, delta, tau, K, W_list, W_miss, idx1, idx0, n_iter, n_burnin, n_thin, tol_shift, max_iter_shift));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bayesodt_MCMC_loop", (DL_FUNC) &_bayesodt_MCMC_loop, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_bayesodt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
