# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMC_loop <- function(state, D, mu_a, tau_a, mu_b, tau_b, mu_u, tau_u, gamma, delta, tau, K, W_list, W_miss, idx1, idx0, n_iter, n_burnin, n_thin, tol_shift = 1e-8, max_iter_shift = 200L) {
    .Call(`_bayesodt_MCMC_loop`, state, D, mu_a, tau_a, mu_b, tau_b, mu_u, tau_u, gamma, delta, tau, K, W_list, W_miss, idx1, idx0, n_iter, n_burnin, n_thin, tol_shift, max_iter_shift)
}

